# version: '3.8'
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=azerty
#     ports:
#       - '5433:5432'
